Repository openebs/dynamic-localpv-provisioner, pull requests merged in 2021-05, with the labels that each got.

#49 fix(provisioner): Exits properly if Block volumes is requested without Device StorageType
  cmd/provisioner-localpv/app/provisioner.go
Labels: bug

#51 chore(docs): Remove inconsistency in helm command syntax
  index.md
Labels: documentation

#53 (bugsbash) remove repeat imports
  pkg/kubernetes/api/core/v1/persistentvolume/kubernetes_test.go
  pkg/kubernetes/api/core/v1/persistentvolumeclaim/kubernetes_test.go
  pkg/kubernetes/api/core/v1/pod/kubernetes_test.go
Labels: event/kubecon-eu21-bugbash
